### ISSUE TITLE
Profile link doesn't lead to current user's profile if viewing another user's profile

### ISSUE THREAD

**Issue by djarredon** [iandusenbury/tableland#75]

**Comment by mballeza** [comment]
I think it might be because it only loads a parameter id. Refer to components/professional/index.js
```javascript
  componentWillMount() {
    const { fetchProfessional, match } = this.props
    fetchProfessional(match.params.id)
  }
```
Try a conditional on match, something like this:
```javascript
  componentWillMount() {
    const { fetchProfessional, match } = this.props
    if (match && match.params) fetchProfessional(match.params.id)
    else fetchProfessional('current')
  }
```

**Comment by djarredon** [comment]
This doesn't resolve the issue. I think that, because the page doesn't reload, the match.params is persisting.

**Comment by mballeza** [comment]
Oh I see. Check out the React Component Lifecycle: https://reactjs.org/docs/react-component.html. I bet either componentWillReceiveProps() or componentWillUpdate() will help.

**Comment by djarredon** [comment]
It looks like any of the Updating functions handles the problem, but the way I have it implemented is creating an infinite loop, constantly querying the backend for information. On the frontend it just looks like it's working as intended, but the rails server is looping through the same queries over and over.

**Comment by iandusenbury** [comment]
componentDidUpdate causes a loop on the backend? That's weird.

**Comment by djarredon** [comment]
Maybe I said it weird, but the rails server is being constantly queried when sitting on the /profile or /professional page.

**Comment by iandusenbury** [comment]
Gotcha. Can we just call fetchProfessional() when that button is clicked?

**Comment by djarredon** [comment]
Alright, that's having the desired effect, but now the whole page reloads when the buttons are pressed.

**Comment by iandusenbury** [comment]
damn

**Comment by iandusenbury** [comment]
what does you code look like? `onClick={() => fetchProfessional()}`?

**Comment by djarredon** [comment]
`onClick={() => fetchProfessional('current')}`

**Comment by djarredon** [comment]
Removing `'current'` still returns the correct user, but the reload remains.

**Comment by iandusenbury** [comment]
Hm, what if we don't use the profile route and just use professional/{id} for the current user?

**Comment by djarredon** [comment]
We'd have to pass `this.state.app.user.id` into `{id}`, right? I'm trying it this way and getting an error saying that state is null.

**Comment by iandusenbury** [comment]
https://www.valentinog.com/blog/react-re-render-route-change/

looks like the last solution is what we want

**Comment by iandusenbury** [comment]
fixed it: 
```
componentWillReceiveProps(nextProps) {
    const {
      fetchProfessional,
      location: { pathname: nextPathName }
    } = nextProps
    const { location: { pathname } } = this.props

    if (nextPathName !== pathname) {
      fetchProfessional()
    }
  }
```

**Comment by iandusenbury** [comment]
Is there a branch for this?

**Comment by djarredon** [comment]
Yes, `bugs/profile_link`

**Comment by mballeza** [comment]
I pushed a commit, should work without reloading the page. The issue was that fetchProfessional wasn't added to the container. I have a separate action fetchMapProfessional that initializes the roadmap and reroutes to the home page.

**Comment by djarredon** [comment]
Issue fixed in `bugs/profile_link_fix`
